#!/usr/bin/env bash
#
# Get the repository into the state Vercel should serve, then stop.
#
# Vercel deploys from git, so there is no upload step here and nothing in this
# script talks to the internet. What it does is the three things that must be
# true *in the commit*, because there is no build step on the far side to do
# them:
#
#   1. `app/` holds a current editor build
#   2. `sitemap.xml` describes the pages that actually exist
#   3. every asset URL carries a hash of that asset's contents
#
#   ./scripts/release.sh          do the work, show what changed
#   ./scripts/release.sh --check  fail if anything is stale, leaving the tree as
#                                 it found it
#
# --check answers "would a deploy from this commit serve something wrong?". It
# does the work and then puts the tree back, because the only honest way to know
# whether a build matches the commit is to run the build. It therefore refuses
# to start on a dirty tree: it cannot tell its own output from your edits, and
# restoring would take your work with it.

set -euo pipefail
cd "$(dirname "$0")/.."

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ "$CHECK" = "1" ]; then
  BEFORE="$(git status --porcelain)"
  if [ -n "$BEFORE" ]; then
    echo "--check needs a clean tree: it rebuilds in place and then restores," >&2
    echo "and it cannot tell its own output from your uncommitted changes." >&2
    echo >&2
    git status --short >&2
    exit 2
  fi
fi

echo "==> Building the editor"
npm --prefix builder run build

echo "==> Regenerating sitemap.xml"
python3 scripts/sitemap.py .

# ---------------------------------------------------------------------------
# Stamp every stylesheet, script and image reference with a hash of its own
# contents.
#
# This used to happen while assembling a `dist/` directory, which meant the
# repository could carry hand-written `?v=31` numbers and nobody had to keep
# them honest. Vercel serves the repository itself, so the stamp has to be in
# the commit — and it has to be derived rather than remembered, because
# `vercel.json` serves `/assets/*` as `immutable` for a year. `immutable` means
# browsers will not revalidate even on a forced reload, so an unstamped image is
# a file you cannot replace for twelve months without renaming it.
# ---------------------------------------------------------------------------
echo "==> Stamping asset versions from file contents"
python3 - <<'STAMP'
import hashlib, pathlib, re

root = pathlib.Path(".")

# `app/assets/*` is deliberately absent: Vite already puts a content hash in
# those filenames, so stamping them would be a hash of a hash.
patterns = ["assets/css/*.css", "assets/js/*.js",
            "assets/images/**/*", "assets/og-image.png"]
digests = {}
for pat in patterns:
    for asset in root.glob(pat):
        if asset.is_file():
            digests[asset.name] = hashlib.sha256(asset.read_bytes()).hexdigest()[:10]

# Any asset path ending in a known extension, with or without an existing ?v=.
# Two prefixes: `assets/...` as written in the HTML, and `../images/...` as
# written by url() inside assets/css — the same file reached two ways.
EXT = r'(?:css|js|png|jpe?g|webp|avif|svg|gif|ico|woff2?)'
pattern = re.compile(
    r'((?:assets/|\.\./)(?:[A-Za-z0-9_-]+/)*'
    r'([A-Za-z0-9_.-]+\.' + EXT + r'))'
    r'(\?v=[^"\'\)\s]*)?'
)

def stamp(match):
    path, name, _ = match.groups()
    digest = digests.get(name)
    return f"{path}?v={digest}" if digest else match.group(0)

# Only the site's own pages. `app/index.html` is generated by Vite and already
# points at hashed filenames.
def targets():
    return list(root.glob("*.html")) + list(root.glob("assets/css/*.css")) + [root / "site.webmanifest"]

changed = 0
for page in targets():
    if not page.exists():
        continue
    text = page.read_text(encoding="utf-8")
    updated = pattern.sub(stamp, text)
    if updated != text:
        page.write_text(updated, encoding="utf-8")
        changed += 1

# CSS is hashed by content, so stamping inside it changes it — rehash and
# restamp the HTML that points at it, or every page would request the old digest.
for asset in root.glob("assets/css/*.css"):
    digests[asset.name] = hashlib.sha256(asset.read_bytes()).hexdigest()[:10]
for page in targets():
    if not page.exists():
        continue
    text = page.read_text(encoding="utf-8")
    updated = pattern.sub(stamp, text)
    if updated != text:
        page.write_text(updated, encoding="utf-8")

print(f"    {changed} files stamped, {len(digests)} assets hashed")
STAMP

# A deploy that quietly shipped a stale editor would be worse than a failed one.
[ -f app/index.html ] || { echo "ERROR: app/index.html is missing — the editor did not build." >&2; exit 1; }
[ -d app/assets ]     || { echo "ERROR: app/assets is missing — the editor did not build." >&2; exit 1; }

# Vite compiles VITE_NEON_DATA_URL *into* the bundle, so a build without it
# produces an editor where `cloudConfig()` is null, the account panel hides
# itself, and sign-in is simply absent — with no error anywhere to say why.
# Checking the artefact rather than the variable is the point: it catches a
# missing .env.local, a typo in the name, and a stale bundle alike.
if ! grep -q 'apirest' app/assets/index-*.js 2>/dev/null; then
  echo
  echo "WARNING: the editor bundle carries no Data API URL." >&2
  echo "  Sign-in will not appear on the deployed site — the account UI hides" >&2
  echo "  itself when there is no cloud project configured." >&2
  echo >&2
  echo "  Put this in builder/.env.local and re-run:" >&2
  echo "    VITE_NEON_DATA_URL=https://ep-xxx.apirest.<region>.aws.neon.tech/neondb/rest/v1" >&2
  echo >&2
  echo "  (Intentional for a local-only build — see docs/CLOUD.md.)" >&2
fi

echo
if [ "$CHECK" = "1" ]; then
  AFTER="$(git status --porcelain)"
  # Put the tree back before reporting, so a failed check never leaves a
  # half-built bundle behind for someone to commit by accident. The tree was
  # verified clean above, so this discards only what this run produced.
  git checkout -- . 2>/dev/null || true
  git clean -qfd app 2>/dev/null || true
  if [ -n "$AFTER" ]; then
    echo "STALE — the commit does not match what a build produces:" >&2
    printf '%s\n' "$AFTER" | sed 's/^/  /' >&2
    echo >&2
    echo "Run ./scripts/release.sh and commit the result." >&2
    exit 1
  fi
  echo "Up to date: the bundle, the sitemap and every asset stamp match the sources."
  exit 0
fi

if git diff --quiet; then
  echo "Nothing changed — already up to date."
else
  echo "Changed:"
  git diff --stat | sed 's/^/  /'
  echo
  echo "Review, commit and push. Vercel deploys from git."
fi
